# Generated by Django 4.1.3 on 2022-11-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('image', models.ImageField(upload_to='static/menu')),
                ('slug', models.SlugField(max_length=99, unique=True)),
            ],
        ),
    ]
